### PR TITLE
Get the tests passing again

### PR DESCRIPTION
**Pull request by patrickbkr**
Please do review. I mostly don't know what I'm doing here...

### CODE REVIEW

**Comment by Altai-man** [comment]
At least the spec bit makes sense 100%.

**Comment by patrickbkr** [comment]
Ping @timo, @Altai-man.

Related question: Who currently feels responsible for this repo? I.e. who should I actually ping? If it's dormant, can we move to raku-community-modules?

**Comment by Altai-man** [comment]
Hi!

I am mostly keeping myself away from programming. The tests indeed pass on recent Rakudo and the changes look sensible, so I will merge it. Thanks for the ping.

**Comment by jnthn** [comment]
>  If it's dormant, can we move to raku-community-modules?

Transferred.

**Pull request merged**
